//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: common.proto
namespace common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test4")]
  public partial class test4 : global::ProtoBuf.IExtensible
  {
    public test4() {}
    
    private int _f = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"f", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int f
    {
      get { return _f; }
      set { _f = value; }
    }
    private string _ccc = @"asdasdasd";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ccc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"asdasdasd")]
    public string ccc
    {
      get { return _ccc; }
      set { _ccc = value; }
    }
    private string _cmd_data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cmd_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cmd_data
    {
      get { return _cmd_data; }
      set { _cmd_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test3")]
  public partial class test3 : global::ProtoBuf.IExtensible
  {
    public test3() {}
    
    private int _d = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"d", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int d
    {
      get { return _d; }
      set { _d = value; }
    }
    private common.test4 _cc = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.test4 cc
    {
      get { return _cc; }
      set { _cc = value; }
    }
    private string _named = @"asdasdasd";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"named", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(@"asdasdasd")]
    public string named
    {
      get { return _named; }
      set { _named = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"client_info")]
  public partial class client_info : global::ProtoBuf.IExtensible
  {
    public client_info() {}
    
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private int _use_icon = (int)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"use_icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int use_icon
    {
      get { return _use_icon; }
      set { _use_icon = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"match_player")]
  public partial class match_player : global::ProtoBuf.IExtensible
  {
    public match_player() {}
    
    private int _uid = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _country = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"country", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int country
    {
      get { return _country; }
      set { _country = value; }
    }
    private int _icon = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _race = (int)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"race", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int race
    {
      get { return _race; }
      set { _race = value; }
    }
    private int _race_level = (int)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"race_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int race_level
    {
      get { return _race_level; }
      set { _race_level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}