//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
// Note: requires additional types generated from: common.proto
namespace login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test2")]
  public partial class test2 : global::ProtoBuf.IExtensible
  {
    public test2() {}
    
    private int _c = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"c", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int c
    {
      get { return _c; }
      set { _c = value; }
    }
    private readonly global::System.Collections.Generic.List<common.test3> _ss = new global::System.Collections.Generic.List<common.test3>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<common.test3> ss
    {
      get { return _ss; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test1")]
  public partial class test1 : global::ProtoBuf.IExtensible
  {
    public test1() {}
    
    private int _a = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"a", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int a
    {
      get { return _a; }
      set { _a = value; }
    }
    private readonly global::System.Collections.Generic.List<login.test2> _b = new global::System.Collections.Generic.List<login.test2>();
    [global::ProtoBuf.ProtoMember(2, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<login.test2> b
    {
      get { return _b; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_login")]
  public partial class req_login : global::ProtoBuf.IExtensible
  {
    public req_login() {}
    
    private int _flag = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"rsp_login")]
  public partial class rsp_login : global::ProtoBuf.IExtensible
  {
    public rsp_login() {}
    
    private int _result = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _game_time = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"game_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int game_time
    {
      get { return _game_time; }
      set { _game_time = value; }
    }
    private int _status = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private common.client_info _client_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"client_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public common.client_info client_info
    {
      get { return _client_info; }
      set { _client_info = value; }
    }
    private login.test1 _test = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"test", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public login.test1 test
    {
      get { return _test; }
      set { _test = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ntf_logout")]
  public partial class ntf_logout : global::ProtoBuf.IExtensible
  {
    public ntf_logout() {}
    
    private int _reason = (int)0;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}