//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/protocol_c2s.proto
namespace cs
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"req_login")]
  public partial class req_login : global::ProtoBuf.IExtensible
  {
    public req_login() {}
    

    private int _flag = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSMessage")]
  public partial class CSMessage : global::ProtoBuf.IExtensible
  {
    public CSMessage() {}
    
    private uint _TypeId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TypeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TypeId
    {
      get { return _TypeId; }
      set { _TypeId = value; }
    }
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data; }
      set { _Data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoginInfo")]
  public partial class CSLoginInfo : global::ProtoBuf.IExtensible
  {
    public CSLoginInfo() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoginReq")]
  public partial class CSLoginReq : global::ProtoBuf.IExtensible
  {
    public CSLoginReq() {}
    
    private string _UserName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"UserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UserName
    {
      get { return _UserName; }
      set { _UserName = value; }
    }
    private string _Password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Password
    {
      get { return _Password; }
      set { _Password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CSLoginRes")]
  public partial class CSLoginRes : global::ProtoBuf.IExtensible
  {
    public CSLoginRes() {}
    
    private uint _result_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result_code
    {
      get { return _result_code; }
      set { _result_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EnmCmdID")]
    public enum EnmCmdID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN_REQ", Value=10001)]
      CS_LOGIN_REQ = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CS_LOGIN_RES", Value=10002)]
      CS_LOGIN_RES = 10002
    }
  
}